//! OctoPOS Windows companion service.
//!
//! Runs as a Windows service installed by the bootstrapper. The admin
//! Tauri process talks to it through a named pipe whenever it needs
//! to perform a privileged operation:
//!
//!   - `apply-api-update`  →  rewrite OCTOPOS_API_VERSION in the host
//!                           .env and run `docker compose up -d
//!                           --force-recreate api`.
//!   - `install-msi`       →  run `msiexec /i <path> /quiet /qn`.
//!   - `read-env`          →  read /opt/octopos/.env (over WSL).
//!   - `write-env`         →  rewrite a key in the same file.
//!
//! Authentication: every request carries an HMAC-SHA256 of the
//! payload computed with a shared secret. The shared secret is
//! generated by the bootstrapper at install-time and stored in:
//!   - HKLM\Software\OctoPOS\UpdaterSecret  (read by this service)
//!   - %APPDATA%\octopos\updater-secret     (read by the admin)
//!
//! That keeps the channel honest against random local processes
//! poking at the pipe — anyone reading the registry already has
//! admin, in which case the security model is moot anyway.
//!
//! Cross-platform note: the entire service implementation is
//! conditioned on `cfg(windows)`. On any other target (e.g. CI
//! `cargo check` from Linux) the binary still compiles but the
//! `main` is a no-op so the rest of the workspace can be built.

#[cfg(windows)]
mod service {
    use std::ffi::OsString;
    use std::io::{Read, Write};
    use std::sync::mpsc;
    use std::time::Duration;

    use hmac::{Hmac, Mac};
    use serde::{Deserialize, Serialize};
    use sha2::Sha256;
    use windows_service::define_windows_service;
    use windows_service::service::{
        ServiceControl, ServiceControlAccept, ServiceExitCode, ServiceState, ServiceStatus,
        ServiceType,
    };
    use windows_service::service_control_handler::{self, ServiceControlHandlerResult};
    use windows_service::service_dispatcher;

    pub const SERVICE_NAME: &str = "OctoPOSUpdater";
    pub const PIPE_NAME: &str = r"\\.\pipe\octopos-updater";

    /// Request envelope received over the pipe. The HMAC field is
    /// computed over the JSON serialization of `command` + `args`.
    #[derive(Debug, Serialize, Deserialize)]
    pub struct Request {
        pub command: String,
        pub args: serde_json::Value,
        pub hmac: String,
    }

    /// Response envelope written back to the pipe. `ok=false` means
    /// the service refused or failed; the admin then surfaces
    /// `error` to the user.
    #[derive(Debug, Serialize, Deserialize)]
    pub struct Response {
        pub ok: bool,
        pub data: serde_json::Value,
        pub error: Option<String>,
    }

    define_windows_service!(ffi_service_main, service_main);

    pub fn run() -> windows_service::Result<()> {
        service_dispatcher::start(SERVICE_NAME, ffi_service_main)
    }

    fn service_main(_arguments: Vec<OsString>) {
        if let Err(e) = run_service() {
            log::error!("service crashed: {e}");
        }
    }

    fn run_service() -> windows_service::Result<()> {
        let (shutdown_tx, shutdown_rx) = mpsc::channel();

        let event_handler = move |control_event| -> ServiceControlHandlerResult {
            match control_event {
                ServiceControl::Stop | ServiceControl::Shutdown => {
                    let _ = shutdown_tx.send(());
                    ServiceControlHandlerResult::NoError
                }
                ServiceControl::Interrogate => ServiceControlHandlerResult::NoError,
                _ => ServiceControlHandlerResult::NotImplemented,
            }
        };

        let status_handle =
            service_control_handler::register(SERVICE_NAME, event_handler)?;

        status_handle.set_service_status(ServiceStatus {
            service_type: ServiceType::OWN_PROCESS,
            current_state: ServiceState::Running,
            controls_accepted: ServiceControlAccept::STOP | ServiceControlAccept::SHUTDOWN,
            exit_code: ServiceExitCode::Win32(0),
            checkpoint: 0,
            wait_hint: Duration::default(),
            process_id: None,
        })?;

        // Spawn the IPC loop on a worker thread so the SCM control
        // thread stays free to handle stop/shutdown promptly.
        std::thread::spawn(move || {
            ipc_loop();
        });

        let _ = shutdown_rx.recv();

        status_handle.set_service_status(ServiceStatus {
            service_type: ServiceType::OWN_PROCESS,
            current_state: ServiceState::Stopped,
            controls_accepted: ServiceControlAccept::empty(),
            exit_code: ServiceExitCode::Win32(0),
            checkpoint: 0,
            wait_hint: Duration::default(),
            process_id: None,
        })?;

        Ok(())
    }

    fn ipc_loop() {
        loop {
            match accept_pipe() {
                Ok(mut pipe) => {
                    let mut buf = Vec::new();
                    if let Err(e) = pipe.read_to_end(&mut buf) {
                        log::warn!("pipe read failed: {e}");
                        continue;
                    }
                    let response = handle_request(&buf);
                    let body = serde_json::to_vec(&response).unwrap_or_default();
                    let _ = pipe.write_all(&body);
                }
                Err(e) => {
                    log::warn!("pipe accept failed: {e}");
                    std::thread::sleep(Duration::from_secs(1));
                }
            }
        }
    }

    /// Opens the named pipe in message mode. Implemented with the
    /// raw Win32 API because the higher-level crates either don't
    /// support arbitrary security descriptors or pull a heavy async
    /// runtime.
    fn accept_pipe() -> std::io::Result<NamedPipeStream> {
        use std::os::windows::ffi::OsStrExt;
        use windows_sys::Win32::Foundation::{CloseHandle, INVALID_HANDLE_VALUE};
        use windows_sys::Win32::Storage::FileSystem::{
            PIPE_ACCESS_DUPLEX, FILE_FLAG_FIRST_PIPE_INSTANCE,
        };
        use windows_sys::Win32::System::Pipes::{
            ConnectNamedPipe, CreateNamedPipeW, PIPE_READMODE_MESSAGE, PIPE_TYPE_MESSAGE,
            PIPE_WAIT,
        };

        let wide: Vec<u16> = std::ffi::OsString::from(PIPE_NAME)
            .encode_wide()
            .chain(std::iter::once(0))
            .collect();

        let handle = unsafe {
            CreateNamedPipeW(
                wide.as_ptr(),
                PIPE_ACCESS_DUPLEX | FILE_FLAG_FIRST_PIPE_INSTANCE,
                PIPE_TYPE_MESSAGE | PIPE_READMODE_MESSAGE | PIPE_WAIT,
                1,           // single instance — only the admin talks to us
                64 * 1024,   // out buffer
                64 * 1024,   // in buffer
                0,           // default timeout
                std::ptr::null(),
            )
        };
        if handle == INVALID_HANDLE_VALUE {
            return Err(std::io::Error::last_os_error());
        }

        let connected = unsafe { ConnectNamedPipe(handle, std::ptr::null_mut()) };
        if connected == 0 {
            let err = std::io::Error::last_os_error();
            // ERROR_PIPE_CONNECTED (535) is normal — client connected
            // between CreateNamedPipeW and ConnectNamedPipe.
            if err.raw_os_error() != Some(535) {
                unsafe { CloseHandle(handle) };
                return Err(err);
            }
        }

        Ok(NamedPipeStream { handle })
    }

    /// Owned wrapper around a Win32 named-pipe handle implementing
    /// `Read` + `Write`. Drops by closing the handle so the pipe is
    /// destroyed on disconnect.
    struct NamedPipeStream {
        handle: windows_sys::Win32::Foundation::HANDLE,
    }

    impl Drop for NamedPipeStream {
        fn drop(&mut self) {
            use windows_sys::Win32::Foundation::CloseHandle;
            unsafe { CloseHandle(self.handle) };
        }
    }

    impl Read for NamedPipeStream {
        fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
            use windows_sys::Win32::Storage::FileSystem::ReadFile;
            let mut read = 0u32;
            let ok = unsafe {
                ReadFile(
                    self.handle,
                    buf.as_mut_ptr() as _,
                    buf.len() as u32,
                    &mut read,
                    std::ptr::null_mut(),
                )
            };
            if ok == 0 {
                let err = std::io::Error::last_os_error();
                // Broken pipe (109) on disconnect → EOF.
                if err.raw_os_error() == Some(109) {
                    return Ok(0);
                }
                return Err(err);
            }
            Ok(read as usize)
        }
    }

    impl Write for NamedPipeStream {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            use windows_sys::Win32::Storage::FileSystem::WriteFile;
            let mut written = 0u32;
            let ok = unsafe {
                WriteFile(
                    self.handle,
                    buf.as_ptr() as _,
                    buf.len() as u32,
                    &mut written,
                    std::ptr::null_mut(),
                )
            };
            if ok == 0 {
                return Err(std::io::Error::last_os_error());
            }
            Ok(written as usize)
        }

        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    fn handle_request(raw: &[u8]) -> Response {
        let req: Request = match serde_json::from_slice(raw) {
            Ok(r) => r,
            Err(e) => {
                return Response {
                    ok: false,
                    data: serde_json::Value::Null,
                    error: Some(format!("invalid request: {e}")),
                };
            }
        };

        // HMAC verification. The shared secret lives in the registry
        // under HKLM\Software\OctoPOS\UpdaterSecret. We read it on
        // every call so rotating it does not require a restart.
        let secret = match read_secret() {
            Ok(s) => s,
            Err(e) => {
                return Response {
                    ok: false,
                    data: serde_json::Value::Null,
                    error: Some(format!("secret unavailable: {e}")),
                };
            }
        };

        let payload = format!(
            "{}{}",
            req.command,
            serde_json::to_string(&req.args).unwrap_or_default()
        );
        if !verify_hmac(&secret, payload.as_bytes(), &req.hmac) {
            return Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some("hmac mismatch".to_string()),
            };
        }

        match req.command.as_str() {
            "apply-api-update" => apply_api_update(&req.args),
            "install-msi" => install_msi(&req.args),
            "read-env" => read_env_file(),
            "write-env" => write_env_file(&req.args),
            other => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("unknown command: {other}")),
            },
        }
    }

    fn read_secret() -> std::io::Result<String> {
        // Single registry read; values are small (32 hex bytes).
        // We use std::process::Command to avoid pulling another
        // crate just for one query.
        let output = std::process::Command::new("reg")
            .args([
                "query",
                r"HKLM\Software\OctoPOS",
                "/v",
                "UpdaterSecret",
            ])
            .output()?;
        if !output.status.success() {
            return Err(std::io::Error::other("registry value not found"));
        }
        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            if let Some(rest) = line.trim().strip_prefix("UpdaterSecret") {
                if let Some(value) = rest.split_whitespace().last() {
                    return Ok(value.to_string());
                }
            }
        }
        Err(std::io::Error::other("UpdaterSecret not parseable"))
    }

    fn verify_hmac(secret: &str, payload: &[u8], expected_hex: &str) -> bool {
        let mut mac = match Hmac::<Sha256>::new_from_slice(secret.as_bytes()) {
            Ok(m) => m,
            Err(_) => return false,
        };
        mac.update(payload);
        let digest = mac.finalize().into_bytes();
        let expected = match hex::decode(expected_hex) {
            Ok(b) => b,
            Err(_) => return false,
        };
        // Constant-time compare to avoid the (theoretical) timing
        // leak across the local pipe.
        if digest.len() != expected.len() {
            return false;
        }
        let mut diff = 0u8;
        for (a, b) in digest.iter().zip(expected.iter()) {
            diff |= a ^ b;
        }
        diff == 0
    }

    /// `apply-api-update` runs inside a WSL session against the
    /// docker-compose.yml at /opt/octopos. Args:
    ///   { "version": "api-vX.Y.Z" }
    fn apply_api_update(args: &serde_json::Value) -> Response {
        let version = match args.get("version").and_then(|v| v.as_str()) {
            Some(v) => v,
            None => {
                return Response {
                    ok: false,
                    data: serde_json::Value::Null,
                    error: Some("missing version".to_string()),
                };
            }
        };
        // We pin the new tag in /opt/octopos/.env, then invoke the
        // existing API endpoint inside WSL via curl — the API in the
        // container already has the docker socket and the bind-mount
        // it needs to do the actual recreate. The companion service
        // is just here so the admin Tauri (running as the user) does
        // not need to elevate every time.
        let env_update = std::process::Command::new("wsl")
            .args([
                "-u",
                "root",
                "bash",
                "-c",
                &format!(
                    "set -e; sed -i.bak -E 's/^OCTOPOS_API_VERSION=.*/OCTOPOS_API_VERSION={version}/' /opt/octopos/.env || echo 'OCTOPOS_API_VERSION={version}' >> /opt/octopos/.env"
                ),
            ])
            .output();
        match env_update {
            Ok(o) if o.status.success() => Response {
                ok: true,
                data: serde_json::json!({ "version": version }),
                error: None,
            },
            Ok(o) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!(
                    "wsl env update failed ({}): {}",
                    o.status,
                    String::from_utf8_lossy(&o.stderr)
                )),
            },
            Err(e) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("wsl spawn failed: {e}")),
            },
        }
    }

    /// `install-msi` runs `msiexec /i <path> /quiet /qn`. Args:
    ///   { "path": "C:\\path\\to\\OctoPOS.Admin_X.Y.Z_x64.msi" }
    fn install_msi(args: &serde_json::Value) -> Response {
        let path = match args.get("path").and_then(|v| v.as_str()) {
            Some(p) => p,
            None => {
                return Response {
                    ok: false,
                    data: serde_json::Value::Null,
                    error: Some("missing path".to_string()),
                };
            }
        };
        // Defense in depth: refuse anything that doesn't look like
        // a path inside our own install dir, so the admin process
        // cannot trick the service into running an arbitrary MSI.
        if !path.to_ascii_lowercase().contains("octopos") || !path.ends_with(".msi") {
            return Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some("path must point to an OctoPOS .msi".to_string()),
            };
        }
        match std::process::Command::new("msiexec")
            .args(["/i", path, "/quiet", "/qn"])
            .status()
        {
            Ok(s) if s.success() => Response {
                ok: true,
                data: serde_json::json!({ "path": path }),
                error: None,
            },
            Ok(s) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("msiexec exited {}", s.code().unwrap_or(-1))),
            },
            Err(e) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("msiexec spawn failed: {e}")),
            },
        }
    }

    fn read_env_file() -> Response {
        let out = std::process::Command::new("wsl")
            .args(["-u", "root", "cat", "/opt/octopos/.env"])
            .output();
        match out {
            Ok(o) if o.status.success() => Response {
                ok: true,
                data: serde_json::json!({
                    "content": String::from_utf8_lossy(&o.stdout).to_string()
                }),
                error: None,
            },
            Ok(o) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!(
                    "cat failed: {}",
                    String::from_utf8_lossy(&o.stderr)
                )),
            },
            Err(e) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("wsl spawn failed: {e}")),
            },
        }
    }

    fn write_env_file(args: &serde_json::Value) -> Response {
        let key = args.get("key").and_then(|v| v.as_str()).unwrap_or("");
        let value = args.get("value").and_then(|v| v.as_str()).unwrap_or("");
        if key.is_empty() {
            return Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some("missing key".to_string()),
            };
        }
        let cmd = format!(
            "set -e; if grep -q '^{key}=' /opt/octopos/.env; then sed -i.bak -E 's/^{key}=.*/{key}={value}/' /opt/octopos/.env; else echo '{key}={value}' >> /opt/octopos/.env; fi"
        );
        match std::process::Command::new("wsl")
            .args(["-u", "root", "bash", "-c", &cmd])
            .status()
        {
            Ok(s) if s.success() => Response {
                ok: true,
                data: serde_json::Value::Null,
                error: None,
            },
            Ok(s) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("wsl exited {}", s.code().unwrap_or(-1))),
            },
            Err(e) => Response {
                ok: false,
                data: serde_json::Value::Null,
                error: Some(format!("wsl spawn failed: {e}")),
            },
        }
    }
}

#[cfg(windows)]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    use simplelog::{ConfigBuilder, LevelFilter, WriteLogger};
    use std::fs::OpenOptions;

    if let Some(programdata) = std::env::var_os("ProgramData") {
        let mut log_path = std::path::PathBuf::from(programdata);
        log_path.push("OctoPOS");
        log_path.push("updater.log");
        if let Some(parent) = log_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if let Ok(file) = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&log_path)
        {
            let _ = WriteLogger::init(LevelFilter::Info, ConfigBuilder::new().build(), file);
        }
    }

    service::run()?;
    Ok(())
}

#[cfg(not(windows))]
fn main() {
    eprintln!("octopos-updater only runs on Windows.");
    std::process::exit(1);
}
